### PR TITLE
Pointer smoothing and aim assist

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Added a smoothing option to the Pointer, which stabilises the laser in case of shaky movements. Two aiming assistance were also added, a snapping assistance, which snaps the laser to the center of the closest Mole, and a magnetizing assistance, which pulls the laser towards the closest Mole. Both of these aiming assistance can also be smoothed. These aiming assistance are to be used when the participant manages to point at the moles but isn't precise enouth to reliably hit them. While the magnetizing assistance still takes into account the precision of the aim, the snapping assistance ignores it totally to focus solely on the participant's sighting.

Pointer raw, note the wobble when shooting due to the trigger being pressed:
s_raw

Pointer with smooth, there is a slight latency between the laser and where the Pointer really points at, but the wobble caused by the trigger being pressed is dampened:
s_smooth

Pointer with snap, the laser always points right at the center of the closest Mole:
s_snap

Pointer with magnet, the magnet assures that the laser always points at a Mole, but doesn't constrain it to the center of the Mole:
s_magnet

Pointer with smoothed snap, makes the snapping less disturbing:
s_snap_smooth

Pointer with smoothed magnet, makes the magnetizing less disturbing. Actually, when in-game, the smoothed magnetizing feels really natural:
s_magnet_smooth
I love gifs!

Also fixed a few issues with the Mole class, and the GameDirector.

### CODE REVIEW

**Comment by QuentinDaveau** [comment]
@bastianilso Currently there is no log corresponding to the pointer's pointing direction. The closes one would be ControllerLaserPos(Local/World) - ControllerPos(Local/World), which would correspond to the pointer's pointing direction **with the modifier (smoothing, snapping...)**. 

Logging the Pointer's aimed direction (one raw, and one with current modifier) is a good idea, I'll implement it before merging the branch. I'll also add two more columns to the database, one for the smoothing (on/off), and one for the aim assist (none, snap, magnet).

**Comment by YoNeXia** [comment]
I do not why but I can make infinity reviews... Why not?

**Comment by QuentinDaveau** [comment]
Rebased branch after merging of #46

**Comment by QuentinDaveau** [comment]
Added the new logs. Since it is a very minor change in the code, I don't think a new review is necessary. Thereby, a merge it is!

**Pull request merged**
