### PR TITLE
Laser overhaul

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Overhaul of the Pointer class (the laser). A Cursor class has been created to add more cotrol over the cursor's behavior (object placed at the tip of the laser when it hits something), and revamped the BasicPointer class' shooting effect. The new laser with its shooting effect:

overhauled_laser
Pew, Pew Pew!

### CODE REVIEW

**Comment by bastianilso** [comment]
Very cool @QuentinDaveau ! :cat: 

There is just some minor adjustments to the color changes:
**Hovering over a target** should give a less strong white, it needs a slight down-tone (-25%).
Screenshot from 2019-11-13 08-00-18

**Shooting a target** should turn the mole completely white. Secondly, the laser-beam needs to become a stronger green. Right now, the green is a bit too weak.
Screenshot from 2019-11-13 08-00-10

Currently, **Missing a target** turns red, but we need to get the other equivalently strong, so it wont feel overpowering.
Screenshot from 2019-11-13 08-03-30

**Comment by bastianilso** [comment]
@QuentinDaveau me and Hendrik also talked about making the mole "bubble in", ie, make it move backwards and forward again in response to the shot. A bit like hitting a button.

**Comment by QuentinDaveau** [comment]
@bastianilso 
For any issue concerning the Mole, this will be changed and fixed in issue #3. This current issue only concerns the laser, so I think we should stick to it. I added your comments to #3.

For any change to the laser, I agree that the colors aren't well balanced. I'll do the change right now.

**Comment by bastianilso** [comment]
great, thanks @QuentinDaveau and good point - that would fit into issue #3 well. :)

**Comment by QuentinDaveau** [comment]
@bastianilso The laser colors has been arranged. The green color is more contrasted and the white laser (when not shooting) is more faded. Sadly no gif this time since I don't want to spend another hour tinkering with the gif so github would accept it :D (it's just a small color change anyway).

**Comment by QuentinDaveau** [comment]
Also fixed a small bug with the shadows.

**Comment by QuentinDaveau** [comment]
If everything is okay then, it's merging time!

**Pull request merged**
