### PR TITLE
Upgrade Unity 2022.2.1

### PR DESCRIPTION
**Pull request by Xav1204**
@bastianilso I've upgraded Unity to the latest version. In order to have a functional project, we need to do 2 changes in the project.
The first thing to do is to add the script SteamVR_Camera_Helper to the camera. With this script, while the game is running, we will have a component Tracked Pose Driver that will be added to work with Open XR and move the camera in the vr environment.
image
The other thing to do is to disable CameraDisp2 in the CameraRig hierarchy : 
image
Indeed, this camera comes into conflict with the main camera in the CameraRig object. When this camera is disabled, we can see that the instruction panel appears in the play mode.
image
I also tested in the build and it's still right. We have any problem with the executable.

### CODE REVIEW

**Comment by bastianilso** [comment]
@Xav1204 are you aware what function the CameraDisp2 camera object serves in the game? and what consequences it has to disable the camera?

Also, if you could please play the Mirror Therapy treatment program and attach a zip with the meta/event/sample CSV files here, I'll help with verifying everything is in order by running through the produced data.

**Comment by Xav1204** [comment]
@bastianilso I've made the zip with the datas of the Mirror therapy program. I activated the eye tracking during the session like that you will able to check if the eye tracking is right also.
[MirrorTherapy.zip](https://github.com/med-material/Whack_A_Mole_VR/files/10489582/MirrorTherapy.zip)

Tell me if it's right after the verification. Like that, I will push the changes on github and we could make the merge.

**Comment by bastianilso** [comment]
@Xav1204 I have checked the data and from the outset, it seems to look good. [I tried testing it with aldryck's data visualization](https://github.com/med-material/d3-rshiny-vis/pull/19) but i think there might be some bugs in his visualization. anyway, I'm waiting for him to get back to me, but I think you can start preparing the pull request with your changes. please document carefully what needs changing and why. Thanks!

**Comment by Xav1204** [comment]
@bastianilso 
The first thing that I've made is to change the script on this background object : 
image
Indeed, we had the component Enable During Calibration and the problem is that as this component wasn't disable after the calibration, we have this kind of window that we had in the vr headset that cause the problem of rendering. 
image
Now, we use the component Disable During Calibration, so like that, during the calibration, our white background is disabled during the calibration and it will be available after the calibration.

**Comment by bastianilso** [comment]
@Xav1204 the GreyBackground object is supposed to be enabled only during calibration. This is why it carries the EnableDuringCalibration script. It's not clear to me what this has to do with the bug you were trying to fix, can you elaborate?

**Comment by Xav1204** [comment]
@bastianilso When I removed the greybackground (whitemat) in the calibration panel, I obtained this result :
image

**Comment by bastianilso** [comment]
@Xav1204 Okay.. What is going on...

**Comment by bastianilso** [comment]
@Xav1204 what we need to understand here:

- Are the GreyBackgroundPanel objects causing the problem or preventing the problem?
- If they cause the problem, what happens when both are removed? what components on the objects are at fault?
- If they prevent the problem, then we need to identify what then causes the problem. Does removing all objects in the scene prevent the problem? Does changing the Sky/Environment to Unity's default somehow fix the problem?

**Comment by Xav1204** [comment]
@bastianilso It's good, 
I've changed the OpenVr parameter Stereo Rendering Mode in multi pass as I explained you: 
image
And I've also removed the WhiteMat background : 
image

**Comment by Xav1204** [comment]
@bastianilso I forgot if I need to add again the white background that we had ?
If it's not the case, we can merge this pull request.

**Pull request merged**
