### PR TITLE
Mole as disk

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Pull request for issue #26 
Replaced the current ball moles with disk moles. They are basically the same but the disk moles are flat disks:

image

Also added a new log entry corresponding to where the Mole was hit (in X and Y coordinates), as requested in the issue.

### CODE REVIEW

**Comment by YoNeXia** [comment]
I think is necesserary to do another commit for all new organization. Into the decription of the new commit, explain quickly why and how you re-organize files. And you can explain precisely the organization with screenshots, here, in the pull request discussion.

What do you think about that @bastianilso ?

**Comment by QuentinDaveau** [comment]
It is good to note that it is no major file organization, I just created a few folder to separate the different scripts in categories. I can put the folder creation in its own commit, it's up to you @bastianilso.

**Comment by bastianilso** [comment]
@YoNeXia nice catch. Yes I agree, lets keep that in a separate commit.

**Comment by QuentinDaveau** [comment]
@bastianilso 

> @YoNeXia nice catch. Yes I agree, lets keep that in a separate commit.

Done. Is-it all good for merging ?

**Comment by QuentinDaveau** [comment]
All good. Merging the branch.

**Pull request merged**
