### PR TITLE
Add profile UI and profile managment

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Added profiles and their corresponding UI. A profile is used to store certain parameters/properties to facilitate test presets and follow-up.

A corresponding UI has been added, allowing to select, delete and create a profile from a given name and email (with valid email check). It is mandatory to select a profile to start the game. 

The profile UI in action:
profiles

Profiles are locally saved in the AppData/LocalLow/[project]/UserProfiles folder as *.uprofile files, using the *.ini or *.cgf format style.

### CODE REVIEW

**Comment by QuentinDaveau** [comment]
@bastianilso It can manage profile settings and properties (name and email are actually considered as profile properties). As you said, what is now lacking is an interface implementation to define and select the properties we want to save for each profile. I'll open a new issue for that.

**Comment by bastianilso** [comment]
OK, thanks!

**Comment by QuentinDaveau** [comment]
Forgot to link the profile Email to the saved email in the database. I'll do that before merging.

**Comment by QuentinDaveau** [comment]
Added sync between profile Mail and logged mail.

**Comment by QuentinDaveau** [comment]
@YoNeXia Yep, it is due to the extra features that may be added in the future. It's just so that the next person that may be working on it is aware that it is made to be modified.

**Comment by QuentinDaveau** [comment]
If it is all good, it's merging time !

**Pull request merged**
