### PR TITLE
Add patterns loading and playing

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Added a PatternManager to load and play pattern from files. The pattern
files follow a specific format to control the game. Patterns are saved in the `LocalLow` folder (same as profiles) with the `.wampat` extension.

The pattern can:

- Edit the wall properties;
- Spawn moles and distractors;
- Change modifiers and game parameters;
- Start/stop the game;
- Set the difficulty.

The pattern also supports:

- Comments;
- Random variables;
- Pause mode.

Example of a pattern:

```
WALL:(ROW = 6, COL = 10, SIZEX = 5, SIZEY = 3.2, CURVEX = 0.6, CURVEY = 0.4, MAXANGLE = 80, MOLESCALEX = 30, MOLESCALEY = 30) // Sets a custom wall
WAIT:(TIME=0.5) // Waits 0.5 seconds
REGENRAND:(STARTVALUE=1, ENDVALUE=6, ISINT=true) // Generates a random rounded value between 1 and 6
MOLE:(X = 1, Y = RAND, LIFETIME = 0.25) // Spawns a Mole at X = 1 and Y = random value (previously generated) with a lifetime of 0.25 seconds
MOLE:(X = 10, Y = RAND, LIFETIME = 0.25) // Spawns a Mole at X = 10 and Y = random value (previously generated) with a lifetime of 0.25 seconds
WAIT:(TIME=0.25) // Waits 0.25 seconds
REGENRAND:(STARTVALUE=1, ENDVALUE=6, ISINT=true) // Generates a random rounded value between 1 and 6
MOLE:(X = 2, Y = RAND, LIFETIME = 0.25) // Spawns a Mole at X = 2 and Y = random value (previously generated) with a lifetime of 0.25 seconds
MOLE:(X = 9, Y = RAND, LIFETIME = 0.25) // Spawns a Mole at X = 9 and Y = random value (previously generated) with a lifetime of 0.25 seconds
WAIT:(TIME=0.25)  // Waits 0.25 seconds
REGENRAND:(STARTVALUE=1, ENDVALUE=6, ISINT=true) // Generates a random rounded value between 1 and 6
DISTRACTOR:(X = 3, Y = RAND, LIFETIME = 0.25) // Spawns a Distractor at X = 3 and Y = random value (previously generated) with a lifetime of 0.25 seconds
DISTRACTOR:(X = 8, Y = RAND, LIFETIME = 0.25) // Spawns a Distractor at X = 8 and Y = random value (previously generated) with a lifetime of 0.25 seconds
WAIT:(TIME=0.25) // Waits 0.25 seconds
MOLE:(X = 4, Y = 3, LIFETIME = 0.25) // Spawns a Mole at X = 4 and Y = 3 with a lifetime of 0.25 seconds
MOLE:(X = 7, Y = 3, LIFETIME = 0.25) // Spawns a Mole at X = 7 and Y = 3 with a lifetime of 0.25 seconds
WAIT:(TIME=0.25) // Waits 0.25 seconds
MOLE:(X = 5, Y = 3, LIFETIME = 1) // Spawns a Mole at X = 5 and Y = 3 with a lifetime of 0.25 seconds
MOLE:(X = 6, Y = 3, LIFETIME = 1) // Spawns a Mole at X = 6 and Y = 3 with a lifetime of 0.25 seconds
WAIT:(TIME=1) // Waits 1 seconds
MODIFIER:(MIRROR = True, DUALTASK = True, EYEPATCH = Left, PRISMEFFECT = -15) // Sets the Mirror modifier as True, sets the Dual task modifier as True, sets the Eye patch modifier as Left and sets the Prism effect modifier as -15
DIFFICULTY:(SPEED = Fast) // Sets the difficulty as Fast
WAIT:(TIME=1)
MOLE:(X = 5, Y = 3, LIFETIME = 1)
MOLE:(X = 6, Y = 3, LIFETIME = 1)
WAIT:(TIME=1)
MOLE:(X = 4, Y = 3, LIFETIME = 0.25)
MOLE:(X = 7, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 3, Y = 3, LIFETIME = 0.25)
MOLE:(X = 8, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 2, Y = 3, LIFETIME = 0.25)
MOLE:(X = 9, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.25)
MOLE:(X = 1, Y = 3, LIFETIME = 0.25)
MOLE:(X = 10, Y = 3, LIFETIME = 0.25)
WAIT:(TIME=0.5)
WALL:(ROW = 5, COL = 5, SIZEX = 1, SIZEY = 1, CURVEX = 0.1, CURVEY = 0.1, MAXANGLE = 10, MOLESCALEX = 10, MOLESCALEY = 10)  // Sets a custom wall
MOLE:(X = 2, Y = 2, STARTDELAY = 0.25, LIFETIME = 1) // Spawns a Mole with a delay
MOLE:(X = 4, Y = 2, STARTDELAY = 0.5, LIFETIME = 0.75) // Spawns a Mole with a delay
MOLE:(X = 4, Y = 4, STARTDELAY = 0.75, LIFETIME = 0.5) // Spawns a Mole with a delay
MOLE:(X = 2, Y = 4, STARTDELAY = 1, LIFETIME = 1) // Spawns a Mole with a delay
DIFFICULTY:(SPEED = Normal) // Sets the difficulty as Normal
MODIFIER:(MIRROR = False, DUALTASK = False, EYEPATCH = None, PRISMEFFECT = 0) // Resets the modifiers
```

The pattern being played:
patterns_ui_update

### CODE REVIEW

**Comment by QuentinDaveau** [comment]
The modifications on the `GameDirector.cs` and stuff are necessary for the patterns to work. I could technically split them into another commit following the pattern one, however this would render the commit implementing the patterns unusable (it would not work if you rebase on it). That's why these modifications are left with the pattern commit, they are tightly linked to the commit and necessary for it to work.

What I can do however is explain it in the commit description, so it's clearer.

**Comment by QuentinDaveau** [comment]
It actually may be possible to split the commit, but I can't assure that the PatternManager will still be working though. I'll test it and split it if it works.

**Comment by bastianilso** [comment]
@QuentinDaveau Nice ⛱ I have some comments related to the exact phrasing/division of the keywords:

`WALL`, `MOLE`, `DISTRACTOR` and `WAIT` seem intuitive to me.
As for REGENRAND, I see why it is useful (and technically powerful), but I find i a bit confusing - based on how you demonstrate it above, it looks like you can use `RAND` in place of anywhere where there is a number - is that right?  Im wondering what kind of pitfalls we run into if it gets used for things like `LIFETIME`, `TIME` and even `ROW` or `COL`, `CURVEX`, `CURVEY`, `CURVEY`, `MIRROR` (which i suppose takes true/false) - could `RAND` end up returning numbers which exceed the maximum/minimum allowed values? What happens if I REGENRAND twice?

I think the file format could be simplified if we design randomness around the concrete use cases, as they appear - this might also make the naming more clear. This could for instance be `MOLERANDOM` and `DISTRACTORRANDOM` - which could take `XMAX` and `YMAX`, `XMIN` and `YMIN` values. Right now from a pattern design perspective, I dont see an idea in allowing moles to have random lifetimes or startdelays - and I think the file format is stronger if we enforce that. Thus we leave less room for bugs or unexpected behavior - and it fits with the idea of having separate types of values declared explicitly.

I am also not sure that we need `DIFFICULTY` - isnt `SPEED` shown as a Modifier in the UI? In that case I would expect to be able to manipulate `SPEED` from the `MODIFIER` statement.

There are a number of other behaviors we need to check for too:
- what happens if I ask the same mole to spawn twice with no delay?
- what happens if I ask the wall to be generated after the game has started?
- Is there a way I can tell the pattern to loop itself? (this might be useful to create "generic sessions" where people can set a specific amount of time from the facilitator UI to train).

**Comment by QuentinDaveau** [comment]
Okay, I managed to split the commit into 2 with a bit of tinkering.

**Comment by hendrikknoche** [comment]
Regarding Bastian's comment above
https://github.com/med-material/Whack_A_Mole_VR/pull/56#issuecomment-572941569
I was wondering if it were possible to have moles launch with zero delay after the hit of a previous mole. meaning that the trigger for the spawn is the hit or its lifetime ends (the latter - lifetime ends - can be addressed with starttime of the mole (n+1) being starttime of other mole (n) plus its lifetime (n). But we cannot launch based on hit. 
Launching after hit has a very nice property that people can choose how fast and with which rhythm they want to play.

**Comment by QuentinDaveau** [comment]
@bastianilso `RAND` can be called anywhere in the pattern. If the value is wrong (if we pass it as an argument which is supposed to be a bool or outside of range), this will raise an error and the incorrect line won't be played (however this shouldn't crash the game and it will continue normally).

`REGENRAND` allows to regen the random value, so if you call it twice you will simply regenerate the random value twice. It is true that it is currently lacking a random bool value (currently it is limited as random float or int). This shouldn't be hard to implement as a parameter to the `REGENRAND` function (`REGENRAND:(BOOL=TRUE)`).

The random function, as well as speed and game control don't have any true uses for now, however they are here to future-proof some possible implementations. That's why I don't think having functions like `MOLERANDOM` is a good idea:

- first, it would mean that, in the future, we would need a random variance for any function that possibly could need it;
- second, such functions prevent different entites to share the same random value (so if we want to do a row of moles at a random height, it is not possible). That's why we currently have the `REGENRAND`, if you don't call it, the `RAND` value is always the same.

`DIFFICULTY` is `SPEED`. The thing is that at the origin (when I started to work on the game), we did refer to the speed of the game as a difficulty ("easy, "medium", "hard", since it does affect more than just the speed of spawn), and the code still uses this designation. 

Currently the `DIFFICULTY` entry just updates the difficulty of the game. It does not speed up the pattern or anything. To do something like that the whole concept of difficulty in the GameDirector would need a rework, since it doesn't affect only the Mole spawn speed but also the Distractor spawn rate, the Mole lifetime...

I can rename `DIFFICULTY` as `SPEED` in the pattern, but we should be careful with the concept of difficulty/speed. A new issue may be needed for this.

Concerning the behaviors:

> what happens if I ask the same mole to spawn twice with no delay?

Nothing. It will spawn once. If you ask a Mole to spawn while it is already active, it will do nothing.

> what happens if I ask the wall to be generated after the game has started?

The wall regenerates, this is actually what happens in the demo (see the gif). The code is solid enough to take it into account and to prevent any error, even if you call a Mole which is outside of the wall range (in this case nothing would happen).

> Is there a way I can tell the pattern to loop itself? (this might be useful to create "generic sessions" where people can set a specific amount of time from the facilitator UI to train).

I thought about creating a `LOOP` function for the pattern, however this would enter in conflict with the way the game calculates the pattern duration. I guess this would be manageable if we enforce every pattern to have a play duration explicitely indicated (maybe ensure that every pattern has a `DURATION` entry at the beginning or something like that). This would need some heavy modifications on the way the game reads and translates the pattern though, so I think this would need its own issue (since a `LOOP` may come with a good set of issues/extra functionalities we may need to take into account).


@hendrikknoche having moles automatically start when the previous Mole has been popped/disabled may be possible, but moles aren't designed to function this way at all. So technically we should be able to implement it, but I think that, if we start to implement some advanced functionalities like this one, we may want to take a step back and consider reworking some of the elements of the game instead of adding functionalities to elements that are not designed to support them in the first hand.

This is actually an issue with the whole project. We are implementing more and more functionalities which weren't planned at all at the beginning, thus we are starting to get a more and more convoluted code (what we call a spaghetti plate). For now the code is still clean enough, but I think this is a good time to think about which functionalities we want for the final product, and rework the classes/code so they are designed to work with them from the beginning. Otherwise the code will start to be less and less usable.

**Comment by bastianilso** [comment]
@hendrikknoche true - hmm, `PATIENTMOLE` ? 😃 
of course, this opens another can of worms - how do we make a random appearing mole which also waits for the previous mole to die.. 
Another option is to transfer these special behavioral properties to some attributes which define which behavior(s) we want, ie.
`MOLE:(RANDOM, PATIENT, XMIN = 0, YMIN = 0, XMAX = 2, YMAX = 5)`

@QuentinDaveau what do you think/propose? 🌮

**Comment by bastianilso** [comment]
Thanks for the informative reply @QuentinDaveau  . I think your remarks are fine - if you judge that at this stage, it is better to leave the implementation like this, then that's what we will do and keep this as a first iteration.

> This is actually an issue with the whole project. We are implementing more and more functionalities which weren't planned at all at the beginning, thus we are starting to get a more and more convoluted code (what we call a spaghetti plate). For now the code is still clean enough, but I think this is a good time to think about which functionalities we want for the final product, and rework the classes/code so they are designed to work with them from the beginning. Otherwise the code will start to be less and less usable.


🌴 
I think an important takeaway is to realize that the conception of an "end product" does not exist - the software development process is more like a spiral of iteration with milestones. As a product improves, new ideas and needs arises to the surface from various perspectives which could not have been foreseen, in this case:

- From the clinicians who wants to use the tool perform diagnosis of diseases.
- From the therapists who wants to use the tool to perform routinely training with patients.
- From the scientists who wants to use the tool conduct controlled experiments and data analysis.
- From the users - the actual users wearing the VR headsets playing the game.

So it is quiet natural that when making issues or designing code, we cannot take into account every possible perspective from the beginning. After the January Experiment, perhaps we can sit down and go through the code structure - and perhaps come up with a new UML diagram, based on the new needs which we have learned about, since your initial codebase rework (and include all the new classes). This might be interesting to compare to the initial UML diagram, you did back in September.

**Comment by QuentinDaveau** [comment]
@bastianilso I agree, this will be interesting to have a look at the progress of the project's code dans class and see how we can redesign things.

**Comment by QuentinDaveau** [comment]
Renamed `REGENRAND` with `RANDGEN`. If everything is good, I merge.

**Comment by bastianilso** [comment]
@QuentinDaveau sounds good.

**Comment by QuentinDaveau** [comment]
Then merge it is !

**Pull request merged**
