### PR TITLE
Add and improve DiskMole's animations

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Pull request referencing issue #3 

Added simple animations to the DiskMole when it changes states (Enable/disable, hover enter/exit, Pop). 

Also improved the colors transition so it is smoother. Previously it was a simple color swap, now it is a tweening between two colors following a [Quart Out ease](https://easings.net/#easeOutQuart).

The new animations are:

- Mole enabling/disabling:

Mole_animations_enable

- Mole hovering:

Mole_animations_hover

- Mole poping:

Mole_animations_hit
Did I told you that I love gifs ?

### CODE REVIEW

**Comment by bastianilso** [comment]
@QuentinDaveau the animations looks good, but the shadow which the moles project on the wall are a bit confusing. The moles should come out of the wall (but be connected to it), rather than appear to levitate in the air.

But other than that, the behavior looks good (hovering, popping, enabling/disabling).

**Comment by hendrikknoche** [comment]
Looks good. Can you add here what happens when you shoot at the background?

**Comment by QuentinDaveau** [comment]
@bastianilso 

> The moles should come out of the wall (but be connected to it), rather than appear to levitate in the air.

I agree, however this may be in conflict with #26. We can change the moles as cylinders, that sticks out of the wall, but this would allow the player to hit them on their sides (this can be an issue for future data analysis). If we change the moles as cylinders, we may want to find a way to force players to hit them on their front only.

Another option could be to simply disable the shadows projected by the moles. Or we could add an "arm" to the moles that hold them to the wall:

image

Let me know what you think of all of this.

> Looks good. Can you add here what happens when you shoot at the background?

When the wall or nothing is hit, the laser plays the "bad hit" animations (see #31). Otherwise nothing else happens.

**Comment by QuentinDaveau** [comment]
Any comment ? Otherwise once @YoNeXia has checked the code, I merge.

**Comment by QuentinDaveau** [comment]
@bastianilso We can, however this will lead to certain moles clipping through the wall when doind certain animations. However this is an issue coming from the unprecise Mole placement at wall generation, so this issue should be resolved with #28 and #34.

**Comment by QuentinDaveau** [comment]
> However this is an issue coming from the unprecise Mole placement at wall generation

We can easily see on the gifs that the moles at the center of the wall are closer than the moles on the sides

**Comment by QuentinDaveau** [comment]
Merge it is then !

**Pull request merged**
