### PR TITLE
Add SQL integration

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Added upload of the logs to the SQL database through the ConnectToMySQL package. Also added in consequence an option to disable the local saving of the logs (as CSV).

### CODE REVIEW

**Comment by YoNeXia** [comment]
Code and commit are good for me !
Just need to change in your comment and commit, **UploadToMySQL** by **ConnectToMySQL** 😄.

**Comment by QuentinDaveau** [comment]
Good point ^^. I'll fix it.

**Comment by QuentinDaveau** [comment]
Fixed. Since the rest seems okay I'll merge once approved.

**Comment by QuentinDaveau** [comment]
All good then. Merging the branch.

**Pull request merged**
