### PR TITLE
Add exit game key

### PR DESCRIPTION
**Pull request by QuentinDaveau**
Added the possibility to exit the game by pressing the "escape" key.

### CODE REVIEW

**Comment by QuentinDaveau** [comment]
Any idea of other things I should add for the release ?

**Comment by bastianilso** [comment]
@QuentinDaveau how about some error handling of the hardware? What happens if the VR headset disconnects during gameplay, or before starting the game? Can we tell the people that the VR headset is not connected?

Exit game key sounds like a good idea too.

**Comment by QuentinDaveau** [comment]
For now I could try to make a simple warning display if the headset isn't connected. This wouldn't prevent the users from launching the game, like that they could still try it out even without headset. Also, does the ConnectToMySQL has signals to alert if the upload failed or not ? If not this could be a great addition too.

**Comment by bastianilso** [comment]
Could we also have a physical button?
image
[exit-button.zip](https://github.com/med-material/Whack_A_Mole_VR/files/4127553/exit-button.zip)

**Comment by QuentinDaveau** [comment]
Yeah this should be simple to add

**Comment by bastianilso** [comment]
@QuentinDaveau for writing data to the database, we will just have the whack-a-mole fail silently - from the point of view of the patients/therapists, it is mostly a technicality - they will not be interacting with the data in any way.

Any data that does not get uploaded will just lie on the harddisk as dumped data, so we can extract it/inspeect what data was not uploaded then.

But it is a good idea to emit a signal from ConnectToMySQL on fail that an app can subscribe to. I will add an issue for that.

**Comment by QuentinDaveau** [comment]
Added the exit button as well as a warning message at the bottom-right. The implementation is temporary.

image

I still need to test if the warning correctly works when plugging/unplugging the headset.

**Comment by bastianilso** [comment]
@QuentinDaveau looks good to me - have a test, and lets get this out the door. 🌴 📦 ✉️

**Comment by QuentinDaveau** [comment]
Okay, fixed the code, it all works now. Had an issue with the game UID generation with the standalone version. This has been fixed.

**Comment by QuentinDaveau** [comment]
Rebasing.

**Pull request merged**
