### PR TITLE
Therapist ui implementation

### PR DESCRIPTION
**Pull request by QuentinDaveau**
A therapist UI has been implemented following the indications from issue #4 and #17. It allows the therapist to set the game data (participant Id, game duration and test Id), start, pause and stop the game and set the VR modifiers (mirror effect, prism effect...) as well as the difficulty. The UI can be minimized to a small panel at the bottom-right side of the screen displaying the essential information (game state, if running time left, participant Id and test Id) when unused. An information panel is displayed to the Participant on the front of the wall, giving basic game information (how to play...) when the game is stopped and asking the participant to wait when the game is paused. It is hidden when the game is playing.

therapist_ui

### CODE REVIEW

**Comment by bastianilso** [comment]
Thanks @QuentinDaveau . 

@YoNeXia from an immediate glance at this Quentin's work in this branch, what would you say needs to be done here? (hint: its something you have done on your own branch) 🐑

**Comment by QuentinDaveau** [comment]
If what's needed is to squash, please note that I cannot do it without breaking the Unity scene. I may be able to squash the first commit with the last at best, since it doesn't interacts directly with the therapist UI. The second and third commits are quite importants by themselves and different in feature (second: add the UI without any functionality, third: link the UI to the game). I can squash them if you want but beware, you'll have a ton of scripts and changes in one single commit. The fourth and fifth commits are changes to elements out of the branch's scope (fixes...). I can squash both of them together in a "fixup" commit if you want.

**Comment by bastianilso** [comment]
@QuentinDaveau Don't panic, I was just requesting @YoNeXia to test out your branch and give his thoughts on how the UI might be fine-tuned to the mockups. 🎃 

From my own testing, here are my own thoughts:
- Your VR UI for #4 is pretty spot on. 👍 
- Your Therapist UI is quiet close to where we want to be, in general so that's good. The behavior is more or less exactly like envisioned in #17
- You might want to compare a screenshot of the Therapist UI from Unity with the Therapist UI in the mockups in #17, fx in GIMP. I would like us to get a bit closer to the size (width-to-height ratio) of the design in there.
-  I like your addition of having animation in the therapist UI - how does it feel if we speed it up a bit?

**Comment by QuentinDaveau** [comment]
Ahahah, okay, I talked with yohann and since you got him to squash most of his commits we really thought that was the deal ;D. Do I leave the commits squashed then ? I'll compare the UI with the mockup, and I'll also speed up a bit the animation, it should do no harm.

**Comment by bastianilso** [comment]
> Ahahah, okay, I talked with yohann and since you got him to squash most of his commits we really thought that was the deal ;D. Do I leave the commits squashed then ? I'll compare the UI with the mockup, and I'll also speed up a bit the animation, it should do no harm.

haha, yea apologize for being unclear. :D 
Regarding squashing, do you have a backup branch you can get the original unsquashed commits from? If not, then I suggest you just divide it into one commit for the VR Panel (scripts/prefabs/testing scene) and one commit for the therapist panel.

**Comment by bastianilso** [comment]
@QuentinDaveau great! For animating the dock, have a look at Google's Material design recommendations for speed, for example how long time they spend animating the opening/closing of the dock on Android.

https://material.io/design/motion/speed.html#duration

**Comment by bastianilso** [comment]
> The resized panel compared to the mockup:
> (Image)
> The only element that I didn't change is the "minimize" button, because I think it would be a bit too big if lowered. What is your opinion on it ? Also, be careful your mockup's resolution isn't in 16:9.

- We need to keep some whitespace around the minimize button, otherwise we create tangents with the border of the display. See for instance, the whitespace Windows 10 uses in its top right corner:
image

- I can see what you mean, its my mistake that the mockup is not 16:9, which was otherwise the intention (mentioned in the comment after). I think setting the Preferred Width on the Panel Container gameobject down to a 250 would suffice. If possible, it would be preferable if the dock maintained its size, despite changes in screen width (so it only re-sizes based on screen height).

I will have a look at your code later in the afternoon.

**Comment by QuentinDaveau** [comment]
@bastianilso updated the UI, the animation speed and a few issues in the scripts. It should be good for review now.

**Comment by bastianilso** [comment]
@QuentinDaveau from the demo it looked good. Could you edit the first message here to include screenshots? 

Also, @QuentinDaveau you should now request a code review from @YoNeXia so we make have an extra pair of eyes to ensure that it looks good from a technical point of view. @YoNeXia please write your procedure and findings. ⭐️ 

Once both of you are satisfied, @QuentinDaveau can rebase and merge it. (Please use the dropdown to change the behavior to "Rebase and merge" like in the picture below).

image

**Comment by QuentinDaveau** [comment]
Good, merging and closing the related issues.

**Pull request merged**
