### PR TITLE
Upgrade Camera Rotation

### PR DESCRIPTION
**Pull request by Xav1204**
@bastianilso I've upgraded the camera rotation at the beginning of the game when we close the instruction panel.
So now, we use the fonction ResetZeroPose().
To use this function correctly, we need to change the parameter "Tracking Space Origin" in SteamVR_Settings :
image
As I told you, I've changed the values in the Prism effect slider in order to have a 20° rotation as the glasses :
image
I've made also test on the controller offset and I found that the better values to use for this modifier is -5 and 5 : 
image

### CODE REVIEW

**Comment by bastianilso** [comment]
@Xav1204 for the controller offset, how many meters does the controller move in a "-5 to 5" range? (I presume 1 unit is not 1 meter here, do we multiply it by 0.10 in the code?)

**Comment by Xav1204** [comment]
@bastianilso It's already the case. 
image
So, if we put the controller offset at 3 we will have an offset of 0.3 in X.

**Comment by bastianilso** [comment]
@Xav1204 Ok, so 5,5 means 0.5 meters to the left or to the right, with steps of 0.1 meters. I think that's fine.

**Comment by bastianilso** [comment]
@Xav1204 In that case I would like the prism offset max to be 30 degrees. Maybe with +20 degrees being the default when Prism offset is turned on.

**Comment by Xav1204** [comment]
@bastianilso Is this what you wanted ?
PrismEffect

**Comment by bastianilso** [comment]
@Xav1204 not really.. i think nevermind this part. Let's just stick to the current behavior (therapists might want to gradually induce prism effect anyway).

**Comment by Xav1204** [comment]
@bastianilso ok no problem. I put -20/20 or -30/30?

**Comment by bastianilso** [comment]
@Xav1204 -30/30

**Comment by Xav1204** [comment]
@bastianilso it's good, I've put -30/30.

**Comment by Xav1204** [comment]
@bastianilso Can you merge the pull request please. Like that, I can prepare the last pull request with Aldryck's bug resolution.

**Comment by bastianilso** [comment]
@Xav1204 thanks for notifying, I have merged it now. 👍

**Pull request merged**
